repository: Sayani123M/Sayani123M.github.io
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
title: "My Probability & Trading Blog"
description: "Dissecting classic puzzles and trading strategies"
author: "Sayani Mondal"
