repository: Sayani123M/Sayani123M.github.io
# Site settings
title: "Probability & Trading Blog"
description: "Dissecting classic puzzles and trading strategies"
author: "Sayani Mondal"

url:         "https://Sayani123M.github.io"
baseurl:     ""   # leave blank for user sites

# Theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

# (Optional: future pagination)
# paginate: 5
# paginate_path: "/page/:num/"

