# Site settings
title: "My Probability & Trading Blog"
description: "Dissecting classic puzzles and trading strategies"
author: "Sayani Mondal"

# Theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

# (Optional: future pagination)
# paginate: 5
# paginate_path: "/page/:num/"

